import {
  dining,
  living,
  bedroom,
  kitchen,
  workplace,
  dining1,
  dining2,
  dining3,
  dining4,
  dining5,
  bedroom1,
  bedroom2,
  bedroom3,
  bedroom4,
  bedroom5,
  kitchen1,
  kitchen2,
  kitchen3,
  kitchen4,
  kitchen5,
  livingroom1,
  livingroom2,
  livingroom3,
  livingroom4,
  livingroom5,
  workplace1,
  workplace2,
  workplace3,
  workplace4,
  workplace5,
  inspiration1,
  inspiration2,
  inspiration3,
  inspiration4,
  trophy,
  guarantee,
  shipping,
  support,
  location,
  phone,
  clock,
} from "../assets";

export const navigation = [
  {
    id: "0",
    title: "Home",
    url: "/",
  },
  {
    id: "1",
    title: "Shop",
    url: "/shop",
  },
  {
    id: "2",
    title: "Categories",
    url: "/categories",
  },
  {
    id: "3",
    title: "Contact",
    url: "/contact",
  },
];

export const categories = [
  {
    id: "0",
    title: "Dining room",
    image: dining,
    category: "dining",
    url: "/categories/dining",
  },
  {
    id: "1",
    title: "Living room",
    image: living,
    category: "living",
    url: "/categories/living",
  },
  {
    id: "2",
    title: "Bedroom",
    image: bedroom,
    category: "bedroom",
    url: "/categories/bedroom",
  },
  {
    id: "3",
    title: "Kitchen",
    image: kitchen,
    category: "kitchen",
    url: "/categories/kitchen",
  },
  {
    id: "4",
    title: "Workplace",
    image: workplace,
    category: "workplace",
    url: "/categories/workplace",
  },
];

export const products = [
  {
    id: "0",
    sku: "DIN001",
    image: dining1,
    name: "Quaint Oak",
    price: 85.99,
    category: "dining",
    rating: 4.5,
    popularity: 120,
    isFeatured: false,
    url: "/shop/0",
    description:
      "The Quaint Oak dining table brings a touch of rustic charm to your home. Crafted from solid oak, it features a timeless design that complements both modern and traditional decor. The sturdy construction ensures durability for everyday use.",
  },
  {
    id: "1",
    sku: "DIN002",
    image: dining2,
    name: "Modern Wave",
    price: 129.0,
    category: "dining",
    rating: 4.0,
    popularity: 95,
    isFeatured: false,
    url: "/shop/1",
    description:
      "The Modern Wave dining table stands out with its sleek design and smooth, curved lines. Made from high-quality materials, it is designed to offer both style and functionality. This table is perfect for contemporary dining spaces.",
  },
  {
    id: "2",
    sku: "DIN003",
    image: dining3,
    name: "Curve",
    price: 142.5,
    category: "dining",
    rating: 4.7,
    popularity: 130,
    isFeatured: true,
    url: "/shop/2",
    description:
      "The Curve dining table combines elegance and practicality. Its smooth, rounded edges and polished finish make it a centerpiece in any dining room. The sturdy frame ensures it can withstand daily use while maintaining its sophisticated look.",
  },
  {
    id: "3",
    sku: "DIN004",
    image: dining4,
    name: "Rustic",
    price: 112.3,
    category: "dining",
    rating: 4.2,
    popularity: 110,
    isFeatured: false,
    url: "/shop/3",
    description:
      "Bring a touch of the countryside to your home with the Rustic dining table. Made from reclaimed wood, each piece is unique with its own natural imperfections. This table is not just a piece of furniture, but a statement of style and sustainability.",
  },
  {
    id: "4",
    sku: "DIN005",
    image: dining5,
    name: "Dine",
    price: 93.75,
    category: "dining",
    rating: 4.3,
    popularity: 85,
    isFeatured: false,
    url: "/shop/4",
    description:
      "The Dine table is a versatile piece that fits seamlessly into any dining area. With its minimalist design and clean lines, it provides a modern look without overpowering your space. The high-quality finish ensures it will stay looking new for years to come.",
  },
  {
    id: "5",
    sku: "LIV001",
    image: livingroom1,
    name: "Cozy Nest",
    price: 199.99,
    category: "living",
    rating: 4.8,
    popularity: 200,
    isFeatured: true,
    url: "/shop/5",
    description:
      "The Cozy Nest sofa offers unparalleled comfort and style. Upholstered in premium fabric, it features plush cushions and a sturdy frame. Its modern design and neutral color make it a perfect fit for any living room setting.",
  },
  {
    id: "6",
    sku: "LIV002",
    image: livingroom2,
    name: "Metro",
    price: 210.45,
    category: "living",
    rating: 4.1,
    popularity: 150,
    isFeatured: true,
    url: "/shop/6",
    description:
      "The Metro coffee table combines functionality with contemporary design. Its sleek glass top and metal frame provide a stylish focal point for your living room. The lower shelf offers additional storage for books, magazines, and other essentials.",
  },
  {
    id: "7",
    sku: "LIV003",
    image: livingroom3,
    name: "Haven",
    price: 178.9,
    category: "living",
    rating: 4.6,
    popularity: 175,
    isFeatured: true,
    url: "/shop/7",
    description:
      "The Haven armchair is designed for maximum comfort and relaxation. Its ergonomic design supports your body perfectly, while the high-quality fabric and cushioned seating provide a luxurious feel. Ideal for any living room or reading nook.",
  },
  {
    id: "8",
    sku: "LIV004",
    image: livingroom4,
    name: "Chic Corner",
    price: 205.0,
    category: "living",
    rating: 4.4,
    popularity: 160,
    isFeatured: true,
    url: "/shop/8",
    description:
      "Chic Corner brings a modern twist to classic design. This sectional sofa features clean lines, a sturdy frame, and soft cushions for added comfort. Its modular design allows for versatile seating arrangements to suit any living space.",
  },
  {
    id: "9",
    sku: "LIV005",
    image: livingroom5,
    name: "Comfort",
    price: 189.99,
    category: "living",
    rating: 4.5,
    popularity: 180,
    isFeatured: true,
    url: "/shop/9",
    description:
      "The Comfort recliner offers the ultimate in relaxation. With its smooth reclining mechanism and plush upholstery, it provides a cozy spot to unwind after a long day. Its classic design and durable construction make it a great addition to any home.",
  },
  {
    id: "10",
    sku: "BED001",
    image: bedroom1,
    name: "Suite",
    price: 250.75,
    category: "bedroom",
    rating: 4.7,
    popularity: 210,
    isFeatured: true,
    url: "/shop/10",
    description:
      "The Suite bed frame combines luxury and functionality. Crafted from high-quality wood, it features a sleek design with a padded headboard for added comfort. Its sturdy construction ensures durability, while the elegant finish adds a touch of sophistication to any bedroom.",
  },
  {
    id: "11",
    sku: "BED002",
    image: bedroom2,
    name: "Sleep",
    price: 245.5,
    category: "bedroom",
    rating: 4.5,
    popularity: 190,
    isFeatured: true,
    url: "/shop/11",
    description:
      "The Sleep mattress is designed for optimal support and comfort. Its multi-layer construction includes memory foam and pocket springs to provide a restful night's sleep. The breathable fabric cover ensures a cool and comfortable sleeping environment.",
  },
  {
    id: "12",
    sku: "BED003",
    image: bedroom3,
    name: "Nook",
    price: 230.0,
    category: "bedroom",
    rating: 4.6,
    popularity: 175,
    isFeatured: true,
    url: "/shop/12",
    description:
      "The Nook nightstand offers both style and functionality. Its compact design fits perfectly beside your bed, while the drawer and open shelf provide convenient storage for your nighttime essentials. The sleek finish and modern design complement any bedroom decor.",
  },
  {
    id: "13",
    sku: "BED004",
    image: bedroom4,
    name: "Quiet",
    price: 215.4,
    category: "bedroom",
    rating: 4.4,
    popularity: 160,
    isFeatured: false,
    url: "/shop/13",
    description:
      "The Quiet dresser combines ample storage with a minimalist design. Its clean lines and smooth finish make it a versatile piece that fits seamlessly into any bedroom. The spacious drawers provide plenty of room for clothing, accessories, and more.",
  },
  {
    id: "14",
    sku: "BED005",
    image: bedroom5,
    name: "Nest",
    price: 260.2,
    category: "bedroom",
    rating: 4.8,
    popularity: 220,
    isFeatured: true,
    url: "/shop/14",
    description:
      "The Nest bed frame offers a blend of comfort and style. Its upholstered headboard and sturdy frame provide a supportive and cozy sleeping environment. The modern design and neutral color make it a perfect addition to any bedroom.",
  },
  {
    id: "15",
    sku: "KIT001",
    image: kitchen1,
    name: "Cook Haven",
    price: 175.0,
    category: "kitchen",
    rating: 4.3,
    popularity: 140,
    isFeatured: false,
    url: "/shop/15",
    description:
      "The Cook Haven kitchen island is a perfect blend of style and functionality. It features a spacious countertop for meal preparation and built-in storage shelves for your kitchen essentials. The durable construction and modern design make it a must-have for any kitchen.",
  },
  {
    id: "16",
    sku: "KIT002",
    image: kitchen2,
    name: "Gourmet",
    price: 189.99,
    category: "kitchen",
    rating: 4.5,
    popularity: 180,
    isFeatured: false,
    url: "/shop/16",
    description:
      "The Gourmet kitchen cart adds versatility and convenience to your kitchen. It features a solid wood top, multiple shelves, and a drawer for utensils. The wheels provide easy mobility, allowing you to move it wherever you need extra prep space.",
  },
  {
    id: "17",
    sku: "KIT003",
    image: kitchen3,
    name: "Delight",
    price: 199.0,
    category: "kitchen",
    rating: 4.7,
    popularity: 170,
    isFeatured: false,
    url: "/shop/17",
    description:
      "The Delight dining set includes a stylish table and matching chairs, making it a complete solution for your dining area. The set features a contemporary design with a glass tabletop and metal accents. The comfortable chairs are upholstered in high-quality fabric, providing a perfect blend of style and comfort.",
  },
  {
    id: "18",
    sku: "KIT004",
    image: kitchen4,
    name: "Culinary",
    price: 185.75,
    category: "kitchen",
    rating: 4.4,
    popularity: 160,
    isFeatured: false,
    url: "/shop/18",
    description:
      "The Culinary kitchen cart offers additional storage and prep space for your kitchen. It features a sturdy wooden top, multiple shelves, and a drawer for utensils. The cart is equipped with wheels for easy mobility, making it a versatile addition to any kitchen.",
  },
  {
    id: "19",
    sku: "KIT005",
    image: kitchen5,
    name: "Chef Oasis",
    price: 210.5,
    category: "kitchen",
    rating: 4.6,
    popularity: 200,
    isFeatured: false,
    url: "/shop/19",
    description:
      "The Chef Oasis kitchen island is a stylish and functional piece that enhances your cooking experience. It features a spacious countertop, built-in storage, and a wine rack. The sturdy construction and elegant design make it a perfect centerpiece for your kitchen.",
  },
  {
    id: "20",
    sku: "WOR001",
    image: workplace1,
    name: "Gray",
    price: 150.25,
    category: "workplace",
    rating: 4.2,
    popularity: 120,
    isFeatured: false,
    url: "/shop/20",
    description:
      "The Gray desk offers a modern and functional workspace. It features a large surface area for your computer and other office essentials, as well as built-in storage drawers. The sleek design and neutral color make it a great fit for any home office.",
  },
  {
    id: "21",
    sku: "WOR002",
    image: workplace2,
    name: "Office Hub",
    price: 140.99,
    category: "workplace",
    rating: 4.0,
    popularity: 110,
    isFeatured: false,
    url: "/shop/21",
    description:
      "The Office Hub desk provides a practical and stylish solution for your workspace needs. Its compact design includes a built-in hutch with shelves for additional storage. The sturdy construction and modern look make it ideal for both home and office use.",
  },
  {
    id: "22",
    sku: "WOR003",
    image: workplace3,
    name: "Desk Pro",
    price: 135.75,
    category: "workplace",
    rating: 4.1,
    popularity: 100,
    isFeatured: false,
    url: "/shop/22",
    description:
      "The Desk Pro is designed for productivity and comfort. It features an ergonomic design with adjustable height settings and a spacious work surface. The built-in cable management system helps keep your workspace organized and clutter-free.",
  },
  {
    id: "23",
    sku: "WOR004",
    image: workplace4,
    name: "Space Plus",
    price: 122.5,
    category: "workplace",
    rating: 4.3,
    popularity: 130,
    isFeatured: false,
    url: "/shop/23",
    description:
      "The Space Plus desk offers a minimalist design with maximum functionality. Its clean lines and open shelves provide ample storage without taking up too much space. The durable construction ensures it can handle daily use, making it a great addition to any home office.",
  },
  {
    id: "24",
    sku: "WOR005",
    image: workplace5,
    name: "Aero Desk",
    price: 99,
    category: "workplace",
    rating: 4.2,
    popularity: 140,
    isFeatured: false,
    url: "/shop/24",
    description:
      "The Aero Desk combines style and practicality. Its modern design features a tempered glass top and metal frame, providing a sleek design",
  },
];

export const inspiration = [
  {
    id: 0,
    image: inspiration1,
  },
  {
    id: 1,
    image: inspiration2,
  },
  {
    id: 3,
    image: inspiration3,
  },
  {
    id: 4,
    image: inspiration4,
  },
];

export const help = [
  {
    id: 0,
    title: "Payment Options",
    url: "#payment",
  },
  {
    id: 1,
    title: "Returns",
    url: "#return",
  },
  {
    id: 2,
    title: "Privacy Policies",
    url: "#privacy",
  },
];

export const features = [
  {
    id: 0,
    icon: trophy,
    title: "High Quality",
    text: "crafted from top materials",
  },
  {
    id: 1,
    icon: guarantee,
    title: "Warranty Protection",
    text: "Over 2 years",
  },
  {
    id: 2,
    icon: shipping,
    title: "Free Shipping",
    text: "Order over 150 $",
  },
  {
    id: 3,
    icon: support,
    title: "24/7 Support",
    text: "Dedicated Support",
  },
];

export const contactDetails = [
  {
    id: 0,
    image: location,
    title: "Address",
    text: "236 5th SE Avenue, New York NY10000, United States",
  },
  {
    id: 1,
    image: phone,
    title: "Phone",
    mobile: "Mobile: +(84) 546-6789",
    hotline: "Hotline: +(84) 456-6789",
  },
  {
    id: 2,
    image: clock,
    title: "Working Time",
    weekdays: "Monday-Friday: 9:00 - 22:00",
    weekends: "Saturday-Sunday: 9:00 - 21:00",
  },
];
