import {
    dining,
    living,
    bedroom,
    kitchen,
    workplace,
    dining1,
    dining2,
    dining3,
    dining4,
    dining5,
    bedroom1,
    bedroom2,
    bedroom3,
    bedroom4,
    bedroom5,
    kitchen1,
    kitchen2,
    kitchen3,
    kitchen4,
    kitchen5,
    livingroom1,
    livingroom2,
    livingroom3,
    livingroom4,
    livingroom5,
    workplace1,
    workplace2,
    workplace3,
    workplace4,
    workplace5,
    inspiration1,
    inspiration2,
    inspiration3,
    inspiration4,
} from '../assets';

export const navigation = [
    {
        id: '0',
        title: 'Home',
        url: '/',
    },
    {
        id: '1',
        title: 'Shop',
        url: '/shop',
    },
    {
        id: '2',
        title: 'Categories',
        url: '/categories',
    },
    {
        id: '3',
        title: 'Contact',
        url: '/contact',
    },
];

export const categories = [
    {
        id: '0',
        title: 'Dining room',
        image: dining,
        category: 'dining',
        url: '/categories/dining',
    },
    {
        id: '1',
        title: 'Living room',
        image: living,
        category: 'living',
        url: '/categories/living',
    },
    {
        id: '2',
        title: 'Bedroom',
        image: bedroom,
        category: 'bedroom',
        url: '/categories/bedroom',
    },
    {
        id: '3',
        title: 'Kitchen',
        image: kitchen,
        category: 'kitchen',
        url: '/categories/kitchen',
    },
    {
        id: '4',
        title: 'Workplace',
        image: workplace,
        category: 'workplace',
        url: '/categories/workplace',
    },
];

export const products = [
    {
        id: '0',
        image: dining1,
        name: 'Quaint Oak',
        price: 85.99,
        category: 'dining',
        rating: 4.5,
        popularity: 120,
    },
    {
        id: '1',
        image: dining2,
        name: 'Modern Wave',
        price: 129.0,
        category: 'dining',
        rating: 4.0,
        popularity: 95,
    },
    {
        id: '2',
        image: dining3,
        name: 'Curve',
        price: 142.5,
        category: 'dining',
        rating: 4.7,
        popularity: 130,
    },
    {
        id: '3',
        image: dining4,
        name: 'Rustic',
        price: 112.3,
        category: 'dining',
        rating: 4.2,
        popularity: 110,
    },
    {
        id: '4',
        image: dining5,
        name: 'Dine',
        price: 93.75,
        category: 'dining',
        rating: 4.3,
        popularity: 85,
    },
    {
        id: '5',
        image: livingroom1,
        name: 'Cozy Nest',
        price: 199.99,
        category: 'living',
        rating: 4.8,
        popularity: 200,
    },
    {
        id: '6',
        image: livingroom2,
        name: 'Metro',
        price: 210.45,
        category: 'living',
        rating: 4.1,
        popularity: 150,
    },
    {
        id: '7',
        image: livingroom3,
        name: 'Haven',
        price: 178.9,
        category: 'living',
        rating: 4.6,
        popularity: 175,
    },
    {
        id: '8',
        image: livingroom4,
        name: 'Chic Corner',
        price: 205.0,
        category: 'living',
        rating: 4.4,
        popularity: 160,
    },
    {
        id: '9',
        image: livingroom5,
        name: 'Comfort',
        price: 189.99,
        category: 'living',
        rating: 4.5,
        popularity: 180,
    },
    {
        id: '10',
        image: bedroom1,
        name: 'Suite',
        price: 250.75,
        category: 'bedroom',
        rating: 4.7,
        popularity: 210,
    },
    {
        id: '11',
        image: bedroom2,
        name: 'Sleep',
        price: 245.5,
        category: 'bedroom',
        rating: 4.5,
        popularity: 190,
    },
    {
        id: '12',
        image: bedroom3,
        name: 'Nook',
        price: 230.0,
        category: 'bedroom',
        rating: 4.6,
        popularity: 175,
    },
    {
        id: '13',
        image: bedroom4,
        name: 'Quiet',
        price: 215.4,
        category: 'bedroom',
        rating: 4.4,
        popularity: 160,
    },
    {
        id: '14',
        image: bedroom5,
        name: 'Nest',
        price: 260.2,
        category: 'bedroom',
        rating: 4.8,
        popularity: 220,
    },
    {
        id: '15',
        image: kitchen1,
        name: 'Cook Haven',
        price: 175.0,
        category: 'kitchen',
        rating: 4.3,
        popularity: 140,
    },
    {
        id: '16',
        image: kitchen2,
        name: 'Gourmet',
        price: 189.99,
        category: 'kitchen',
        rating: 4.5,
        popularity: 180,
    },
    {
        id: '17',
        image: kitchen3,
        name: 'Delight',
        price: 199.0,
        category: 'kitchen',
        rating: 4.7,
        popularity: 170,
    },
    {
        id: '18',
        image: kitchen4,
        name: 'Culinary',
        price: 185.75,
        category: 'kitchen',
        rating: 4.4,
        popularity: 160,
    },
    {
        id: '19',
        image: kitchen5,
        name: 'Chef Oasis',
        price: 210.5,
        category: 'kitchen',
        rating: 4.6,
        popularity: 200,
    },
    {
        id: '20',
        image: workplace1,
        name: 'Gray',
        price: 150.25,
        category: 'workplace',
        rating: 4.2,
        popularity: 120,
    },
    {
        id: '21',
        image: workplace2,
        name: 'Office Hub',
        price: 140.99,
        category: 'workplace',
        rating: 4.0,
        popularity: 110,
    },
    {
        id: '22',
        image: workplace3,
        name: 'Desk Pro',
        price: 135.75,
        category: 'workplace',
        rating: 4.1,
        popularity: 100,
    },
    {
        id: '23',
        image: workplace4,
        name: 'Space Plus',
        price: 122.5,
        category: 'workplace',
        rating: 4.3,
        popularity: 130,
    },
    {
        id: '24',
        image: workplace5,
        name: 'Aero Desk',
        price: 99,
        category: 'workplace',
        rating: 4.2,
        popularity: 140,
    },
];

export const inspiration = [
    {
        id: 0,
        image: inspiration1,
    },
    {
        id: 1,
        image: inspiration2,
    },
    {
        id: 3,
        image: inspiration3,
    },
    {
        id: 4,
        image: inspiration4,
    },
];

export const help = [
    {
        id: 0,
        title: 'Payment Options',
        url: '#payment',
    },
    {
        id: 1,
        title: 'Returns',
        url: '#return',
    },
    {
        id: 2,
        title: 'Privacy Policies',
        url: '#privacy',
    },
];
